name: Build and push Docker image to registry

on:
  push:
    branches:
      - main  # Déclenchement lorsque du code est poussé sur main

env:
  REG_NAME: "exo.container-registry.com"  # Nom du registre
  IMAGE_NAME: "backend-app"  # Nom de l’image
  REPOSITORY: "c213-emf"  # Nom du repository dans la registry

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to registry
        run: |
          docker login -u "${{ secrets.USER_NAME }}" -p "${{ secrets.PASSWORD }}" "${{ env.REG_NAME }}"
            - name: buildImage
        run: |
          cd src/backend && docker build -t ${{env.IMAGE_NAME}}:latest .
 
      - name: tageLeBuild
        run: |
          docker tag ${{env.IMAGE_NAME}}:latest "${{env.REG_NAME}}"/c213-emf/${{env.IMAGE_NAME}}:latest
 
      - name: pushImage
        run: |
          docker push "${{env.REG_NAME}}"/c213-emf/${{env.IMAGE_NAME}}:latest