name: Build and push Docker image to registry

on:
  push:
    branches:
      - main  # Déclenchement lorsque du code est poussé sur main

env:
  REG_NAME: "exo.container-registry.com"  # Nom du registre
  IMAGE_NAME: "backend-app"  # Nom de l’image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to registry
        run: |
          docker login -u "${{ secrets.USER_NAME }}" -p "${{ secrets.PASSWORD }}" "${{ env.REG_NAME }}"

      - name: Build Docker image
        run: |
          cd src/backend && docker build -t ${{env.IMAGE_NAME}}:latest .

      - name: Tag the image
        run: |
          docker tag ${{env.IMAGE_NAME}}:latest "${{env.REG_NAME}}"/c213-emf/${{env.IMAGE_NAME}}:latest

      - name: Push the image to registry
        run: |
          docker push ${{ env.REG_NAME }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
